version: 0.1

jobs:
  - name: bronze-ingestion-extraction-job
    schedule:
      quartz_cron_expression: '0 15 22 ? * MON,WED *'
      timezone_id: 'Europe/London'
    parameters:
      report_id: ""
    tasks:
      - task_key: bronze_ingestion-task
        for_each_task:
          inputs:
            - fights
            - actors
            - tables
            - game_data
            - world_data
            - guild_roster
            - player_details
          concurrency: 7
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/01-bronze/bronze-ingestion
          libraries:
            - pypi:
                package: requests_toolbelt
          base_parameters:
            report_id: "${report_id}"
            fight_id: ""
            data_source: "${item}"
      - task_key: bronze_ingestion_events-task
        depends_on:
          - bronze_ingestion-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/01-bronze/bronze-ingestion
          base_parameters:
            report_id: "${report_id}"
            fight_id: ""
            data_source: "events"
      - task_key: bronze_ingestion_logger-task
        depends_on:
          - bronze_ingestion_events-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/01-bronze/bronze-ingestion-logger
      - task_key: bronze_extraction-task
        depends_on:
          - bronze_ingestion_events-task
        for_each_task:
          inputs:
            - fights
            - actors
            - tables
            - game_data
            - world_data
            - guild_roster
            - player_details
            - events
          concurrency: 8
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/01-bronze/bronze-extraction
          base_parameters:
            fight_id: ""
            data_source: "${item}"
      - task_key: bronze_extraction_logger-task
        depends_on:
          - bronze_extraction-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/01-bronze/bronze-extraction-logger

  - name: silver-transformation-validation-job
    trigger:
      pause_status: UNPAUSED
      file_arrival:
        url: /Volumes/01_bronze/warcraftlogs/raw_api_calls/
        min_time_between_triggers_seconds: 86400
        wait_after_last_change_seconds: 600
    tasks:
      - task_key: actors_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-transform-actors
      - task_key: actors_silver_validation-task
        depends_on:
          - actors_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-validate-actors
      - task_key: events_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-transform-events
      - task_key: events_silver_validation-task
        depends_on:
          - events_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-validate-events
      - task_key: fights_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-transform-fights
      - task_key: fights_silver_validation-task
        depends_on:
          - fights_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-validate-fights
      - task_key: tables_silver_transformation-task
        depends_on:
          - fights_silver_validation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-transform-tables
      - task_key: tables_silver_validation-task
        depends_on:
          - tables_silver_transformation-task
        notebook_task:
          notebook_path: /Workspace/.bundle/warcraftlogs-raid-analysis/files/notebooks/02-silver/silver-validate-tables
