name: silver-transformation-validation-job
trigger:
  pause_status: UNPAUSED
  file_arrival:
    url: /Volumes/01_bronze/warcraftlogs/raw_api_calls/
    min_time_between_triggers_seconds: 86400
    wait_after_last_change_seconds: 600
tasks:
  - task_key: actors_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_transform_actors
      source: WORKSPACE
  - task_key: actors_silver_validation-task
    depends_on:
      - task_key: actors_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_validate_actors
      source: WORKSPACE
  - task_key: events_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_transform_events
      source: WORKSPACE
  - task_key: events_silver_validation-task
    depends_on:
      - task_key: events_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_validate_events
      libraries:
        - pypi:
            package: databricks-labs-dqx==0.6.0
      source: WORKSPACE
  - task_key: fights_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_transform_fights
      source: WORKSPACE
  - task_key: fights_silver_validation-task
    depends_on:
      - task_key: fights_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_validate_fights
      libraries:
        - pypi:
            package: databricks-labs-dqx==0.6.0
      source: WORKSPACE
  - task_key: tables_silver_transformation-task
    depends_on:
      - task_key: fights_silver_validation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_transform_tables
      libraries:
        - pypi:
            package: databricks-labs-dqx==0.6.0
      source: WORKSPACE
  - task_key: tables_silver_validation-task
    depends_on:
      - task_key: tables_silver_transformation-task
    notebook_task:
      notebook_path: /Workspace/Users/ricard.mulvany@gmail.com/richmulvany-databricks-projects/warcraftlogs-raid-analysis/notebooks/02-silver/silver_validate_tables
      libraries:
        - pypi:
            package: databricks-labs-dqx==0.6.0
      source: WORKSPACE
queue:
  enabled: true
performance_target: STANDARD
