name: "Databricks: Build"

on:
  workflow_call:
    inputs:
      directory:
        description: The directory containing databricks asset bundle
        type: string
        required: true
      artefact-name:
        description: The name of the artefact to upload
        type: string
        default: databricks-asset-bundle

      outputs:
        artefact-name:
          description: The name of the artefact
          value: ${{ inputs.artefact-name }}
jobs:
  build:
    name: Databricks Asset Bundle
    runs-on: ubuntu-latest
    if: ${{ inputs.directory != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: ${{ inputs.directory }}
      - name: Upload Artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artefact-name }}
          path: ${{ inputs.directory }}
          if-no-files-found: error
        
