- name: Install new Databricks CLI (v0.200+)
  run: |
    pip uninstall -y databricks-cli
    pip install "databricks-cli>=0.200.0"

- name: Check CLI version
  run: databricks --version

- name: Deploy job from YAML
  env:
    DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
    DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  run: |
    databricks jobs deploy --yaml bronze-ingestion-extraction.yaml --overwrite
